{\rtf1\ansi\ansicpg1252\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;\f1\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red67\green67\blue67;\red242\green244\blue249;\red74\green71\blue79;
\red37\green146\blue134;\red71\green91\blue98;}
{\*\expandedcolortbl;;\cssrgb\c33333\c33333\c33333;\cssrgb\c96078\c96471\c98039;\cssrgb\c36078\c34902\c38431;
\cssrgb\c16471\c63137\c59608;\cssrgb\c34510\c43137\c45882;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 remote_theme\cf4 \strokec4 : \cf5 \strokec5 pages-themes/merlot@v0.2.0\cf4 \strokec4 \
\cf2 \strokec2 plugins\cf4 \strokec4 :\
  - \cf5 \strokec5 jekyll-remote-theme\cf4 \strokec4  \cf6 \strokec6 # add this line to the plugins list if you already have one
\f1\fs32 \cf4 \strokec4 \
\
}